### ISSUE TITLE
Ballerina facebook connector - unable to create a facebook client

### ISSUE THREAD

**Issue by hasinidilanka** [wso2-ballerina/module-facebook#11]
**Description:**
I am using ballerina facebook connector to connect to facebook. I have configured the following in my code. The access token is retrieved through facebook Graph API explorer v3.2. I am unable to get a facebook client using the access token. Code is given below.

```
import ballerina/io;
import wso2/facebook;
import ballerina/http;

facebook:FacebookConfiguration facebookConfig = {
    clientConfig:{
        auth:{
            scheme: http:OAUTH2,
            accessToken:"AccessTokenRetrieved"
        }
    }
};

function getPageAccessTokens(facebook:Client facebookclient) {
    io:println("-----------------Requesting page access token------------------");
    var response = facebookclient->getPageAccessTokens("userid");
}

public function main(){
    facebook:Client facebookclient = new(facebookConfig);
   getPageAccessTokens(facebookclient);
}
```

The code is compiling but the facebookclient is empty. Then I tried the same scenario by creating a new endpoint. Code is given below. For this I get the access token for the page.

```
public function main(){

    http:Client clientEP = new("https://graph.facebook.com/pageid?fields=access_token&access_token=AccessTokenRetrieved");

    var resp = clientEP->get("");
    if (resp is http:Response) {
        var payload = resp.getTextPayload();
        if (payload is string) {
            io:println(payload);
        } else {
            io:println(<string> payload.detail().message);
        }
    } else {
        io:println(<string> resp.detail().message);
    }
}
```

**Comment by Biruntha** [comment]
@hasinidilanka 

With Ballerina version 0.991.0 and connector version 0.8.12, the following sample is working fine.
In order to reproduce this issue, may I know which ballerina and connector version are you using?

import ballerina/io;
import wso2/facebook;
import ballerina/http;

facebook:FacebookConfiguration facebookConfig = {
    clientConfig:{
        auth:{
            scheme: http:OAUTH2,
            config: {
                grantType: http:DIRECT_TOKEN,
                config: {
                    accessToken: "EAADKzh4uEyYBAMKgKm3RrxxxxxxxxxxxxxxxxxxyKdtIjk7y3pOLcllZAQLtFRAceQaihocGVtGNDuPzKz6IZAWZCH6EuiddGIMQKI8tOZCCUHuZBkhxh6B7PZAKKOZApyLDqoZAeN6OfemwZDZD"
                }
            }
        }
    }
};


function getPageAccessTokens(facebook:Client facebookclient) {
    io:println("-----------------Requesting page access token------------------");
    var response = facebookclient->getPageAccessTokens("me");
    io:println("Response", response);
}

public function main() {
    facebook:Client facebookclient = new(facebookConfig);
    getPageAccessTokens(facebookclient);
}

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
